export const propertyData = {
    "request": {
      "country": "uk",
      "language": "en",
      "location": "london",
      "num_res": "50",
      "offset": 0,
      "output": "json_xs",
      "page": 1,
      "pretty": "1",
      "product_type": "realestate",
      "property_type": "property",
      "size_type": "net",
      "size_unit": "m2",
      "sort": "newest",
      "bedroom_max": "4",
      "listing_type": "buy",
      "price_max": "650000"
    },
    "response": {
      "application_response_code": "100",
      "application_response_text": "listings returned for one unambiguous location",
      "attribution": {
        "img_height": 22,
        "img_url": "https://resources.nestimg.com/nestoria/img/pbr_v1.png",
        "img_width": 183,
        "link_to_img": "http://www.nestoria.com"
      },
      "created_http": "Wed, 18 Dec 2019 15:00:48 GMT",
      "created_unix": 1576681248,
      "link_to_url": "https://www.nestoria.co.uk/london/property/buy",
      "listings": [
        {
          "bathroom_number": 2,
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "NetHousePrices",
          "img_height": 300,
          "img_url": "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/3.png",
          "img_width": 400,
          "keywords": "Garden, Terraced, Kitchen",
          "latitude": 51.489864,
          "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112856109530934390/title/5/1-1?serpUid=&pt=1&ot=1&l=london&did=90_high3&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.1004078,
          "price": 315000,
          "price_currency": "£",
          "price_formatted": "£315,000",
          "price_high": 315000,
          "price_low": 315000,
          "price_type": "fixed",
          "property_type": "house",
          "size": 0,
          "size_type": "net",
          "summary": "Quick sale guide £325,000. 2 bedroom terraced house through lounge....",
          "thumb_height": 60,
          "thumb_url": "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/4.png",
          "thumb_width": 80,
          "title": "House for sale, London - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 4,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "NetHousePrices",
          "img_height": 300,
          "img_url": "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/4.png",
          "img_width": 400,
          "keywords": "Freehold, Garden, En suite, New Build, Wood Floor, Kitchen, Reception",
          "latitude": 51.486378,
          "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112856108035386428/title/5/1-2?serpUid=&pt=1&ot=1&l=london&did=90_high3&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.0693079,
          "price": 529995,
          "price_currency": "£",
          "price_formatted": "£529,995",
          "price_high": 529995,
          "price_low": 529995,
          "price_type": "fixed",
          "property_type": "house",
          "size": 0,
          "size_type": "net",
          "summary": "This property is an investor's dream project with potential convers...",
          "thumb_height": 60,
          "thumb_url": "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/5.png",
          "thumb_width": 80,
          "title": "House for sale, London - Wood Floor",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "NetHousePrices",
          "img_height": 300,
          "img_url": "https://resources.nestimg.com/nestoria/img/noimage/desktop/flat/5.png",
          "img_width": 400,
          "keywords": "Leasehold, Shared Garden, New Build, Kitchen, Parking, Reception",
          "latitude": 51.485386,
          "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112856108935565823/title/5/1-3?serpUid=&pt=1&ot=1&l=london&did=90_high3&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.0344927,
          "price": 299999,
          "price_currency": "£",
          "price_formatted": "£299,999",
          "price_high": 299999,
          "price_low": 299999,
          "price_type": "fixed",
          "property_type": "flat",
          "size": 0,
          "size_type": "net",
          "summary": "Located in valley grove, and close to charlton main-line surface tr...",
          "thumb_height": 60,
          "thumb_url": "https://resources.nestimg.com/nestoria/img/noimage/mobile/flat/1.png",
          "thumb_width": 80,
          "title": "Flat for sale, London - Reception",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "NetHousePrices",
          "img_height": 300,
          "img_url": "https://resources.nestimg.com/nestoria/img/noimage/desktop/house/4.png",
          "img_width": 400,
          "keywords": "Share of Freehold, Garden, New Build, Fireplace, Wood Floor, Kitchen",
          "latitude": 51.483162,
          "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112856111109201112/title/5/1-4?serpUid=&pt=1&ot=1&l=london&did=90_high3&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.0289494,
          "price": 350000,
          "price_currency": "£",
          "price_formatted": "£350,000",
          "price_high": 350000,
          "price_low": 350000,
          "price_type": "fixed",
          "property_type": "house",
          "size": 0,
          "size_type": "net",
          "summary": "Share of freehold tenure. 2nd floor luxury 2 bed maisonette is now ...",
          "thumb_height": 60,
          "thumb_url": "https://resources.nestimg.com/nestoria/img/noimage/mobile/house/4.png",
          "thumb_width": 80,
          "title": "House for sale, London - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 0,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "PropertyHeads",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedroom_bridgeway_wembley_middlesex_ha0_4dy_112856090878963390.jpg",
          "img_width": 400,
          "keywords": "Garden, Semi-Detached, Kitchen, Off Street Parking, Reception",
          "latitude": 51.5456,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856090878963390/title/5/1-5?serpUid=&pt=1&ot=1&l=london&did=370854_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.290895,
          "price": 499950,
          "price_currency": "£",
          "price_formatted": "£499,950",
          "price_high": 499950,
          "price_low": 499950,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Great opportunity to make this your new family home, right home est...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_bridgeway_wembley_middlesex_ha0_4dy_112856090878963390.jpg",
          "thumb_width": 80,
          "title": "BRIDGEWAY, WEMBLEY, MIDDLESEX, HA0",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 0,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "PropertyHeads",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedroom_lamorna_grove_stanmore_greater_london_112416705278839517.jpg",
          "img_width": 400,
          "keywords": "Garden, Semi-Detached, Double Bedroom, Kitchen, Parking, Patio, Gas Central Heating",
          "latitude": 51.5997,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112416705278839517/title/5/1-6?serpUid=&pt=1&ot=1&l=london&did=370854_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.300417,
          "price": 500000,
          "price_currency": "£",
          "price_formatted": "£500,000",
          "price_high": 500000,
          "price_low": 500000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Three bedroom semi-detached house ? All interest and offers are inv...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_lamorna_grove_stanmore_greater_london_112416705278839517.jpg",
          "thumb_width": 80,
          "title": "Lamorna Grove, Stanmore, Greater London",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_flat_for_sale_112856079947116834.jpg",
          "img_width": 400,
          "keywords": "Wood Floor, Double Bedroom, Kitchen, Reception",
          "latitude": 51.539455,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856079947116834/title/5/1-7?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.246905,
          "price": 525000,
          "price_currency": "£",
          "price_formatted": "£525,000",
          "price_high": 525000,
          "price_low": 525000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Situated on the first floor this corner period property boasting 1,...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_flat_for_sale_112856079947116834.jpg",
          "thumb_width": 80,
          "title": "St. Johns Avenue - Double Bedroom",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 6,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_house_for_sale_112856079268293554.jpg",
          "img_width": 400,
          "keywords": "Garden, Terraced, Wood Floor, Kitchen, Reception, Gas Central Heating",
          "latitude": 51.6294,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856079268293554/title/5/1-8?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.092637,
          "price": 625000,
          "price_currency": "£",
          "price_formatted": "£625,000",
          "price_high": 625000,
          "price_low": 625000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Presenting a bright and extended three bedroom end of terraced hous...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_house_for_sale_112856079268293554.jpg",
          "thumb_width": 80,
          "title": "House for sale, Highfield Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112856080620839440.jpg",
          "img_width": 400,
          "keywords": "Grade II, Gym, Hot tub, Sauna, Double Bedroom, Lift, Porter, Swimming Pool, Gas Central Heating, Listed",
          "latitude": 51.48811,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856080620839440/title/5/1-9?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.01943368,
          "price": 350000,
          "price_currency": "£",
          "price_formatted": "£350,000",
          "price_high": 350000,
          "price_low": 350000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "An and one double bedroom apartment found within a grade ii listed ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112856080620839440.jpg",
          "thumb_width": 80,
          "title": "1 bed flat for sale in Plate House",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 4,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/4_bedrooms_house_for_sale_112856079074091916.jpg",
          "img_width": 400,
          "keywords": "Garden, Semi-Detached, Balcony, Conversion, Garage, Kitchen, Bungalow",
          "latitude": 51.472782,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856079074091916/title/5/1-10?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.068404,
          "price": 600000,
          "price_currency": "£",
          "price_formatted": "£600,000",
          "price_high": 600000,
          "price_low": 600000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 4,
          "size": 0,
          "size_type": "net",
          "summary": "Extensive and views of the london skyline three/four bedrooms 2019 ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/4_bedrooms_house_for_sale_112856079074091916.jpg",
          "thumb_width": 80,
          "title": "Occupation Lane - Bungalow, Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856078894848329.jpg",
          "img_width": 400,
          "keywords": "Shared Garden",
          "latitude": 51.545357,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856078894848329/title/5/1-11?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.226891,
          "price": 500000,
          "price_currency": "£",
          "price_formatted": "£500,000",
          "price_high": 500000,
          "price_low": 500000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Located on a residential road close to willesden green underground ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856078894848329.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Staverton Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_flat_for_sale_112856077261896001.jpg",
          "img_width": 400,
          "keywords": "En suite, No Chain, Balcony, Purpose Built, Kitchen, Parking",
          "latitude": 51.55004,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856077261896001/title/5/1-12?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.110694,
          "price": 335000,
          "price_currency": "£",
          "price_formatted": "£335,000",
          "price_high": 335000,
          "price_low": 335000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "3 bedroom flat for sale chain free 125 years lease. Three bedroom p...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_flat_for_sale_112856077261896001.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Honour Gardens",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_flat_for_sale_112856077611461898.jpg",
          "img_width": 400,
          "keywords": "Double Bedroom",
          "latitude": 51.524117,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856077611461898/title/5/1-13?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.071726,
          "price": 650000,
          "price_currency": "£",
          "price_formatted": "£650,000",
          "price_high": 650000,
          "price_low": 650000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Well located along the vibrant brick lane, moments from trendy hoxt...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_flat_for_sale_112856077611461898.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Brick Lane",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856077051911691.jpg",
          "img_width": 400,
          "keywords": "Balcony, Kitchen, Parking, Reception",
          "latitude": 51.526417,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856077051911691/title/5/1-14?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.020393,
          "price": 475000,
          "price_currency": "£",
          "price_formatted": "£475,000",
          "price_high": 475000,
          "price_low": 475000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Set in a development, this 2 bedroom flat boasts accommodation incl...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856077051911691.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Steward House",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112781796415497265.jpg",
          "img_width": 400,
          "keywords": "Shared Garden, Purpose Built, Double Bedroom, Kitchen, Modern, Parking, Reception, Gas Central Heating, Georgian",
          "latitude": 51.5953,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112781796415497265/title/5/1-15?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.00756291,
          "price": 315000,
          "price_currency": "£",
          "price_formatted": "£315,000",
          "price_high": 315000,
          "price_low": 315000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Two bedroom flat purpose built second floor allocated parking commu...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112781796415497265.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Fulbourne Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_house_for_sale_112781798435788668.jpg",
          "img_width": 400,
          "keywords": "Leasehold, Garden, No Chain, Double Bedroom, Kitchen, Basement, Parking, Reception",
          "latitude": 51.542942,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112781798435788668/title/5/1-16?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.024641689,
          "price": 310000,
          "price_currency": "£",
          "price_formatted": "£310,000",
          "price_high": 310000,
          "price_low": 310000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Upton laneromford roadwoodgrange road investment oppurtunitytwo bed...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_house_for_sale_112781798435788668.jpg",
          "thumb_width": 80,
          "title": "Dunbar Road London E7 - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 1,
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112781797898123663.jpg",
          "img_width": 400,
          "keywords": "Maisonette, Purpose Built, Kitchen, Reception, Edwardian",
          "latitude": 51.451427,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112781797898123663/title/5/1-17?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.187598,
          "price": 515000,
          "price_currency": "£",
          "price_formatted": "£515,000",
          "price_high": 515000,
          "price_low": 515000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Daphne street earlsfield, sw18 515,000 2 bedrooms 1 bathroom 1 rece...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112781797898123663.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Earlsfield - Reception",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_house_for_sale_112856080024069151.jpg",
          "img_width": 400,
          "keywords": "Garden, Terraced, Kitchen, Reception",
          "latitude": 51.580563,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856080024069151/title/5/1-18?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.002381,
          "price": 365000,
          "price_currency": "£",
          "price_formatted": "£365,000",
          "price_high": 365000,
          "price_low": 365000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "A two bedroom terraced house, offering a reception room with space ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_house_for_sale_112856080024069151.jpg",
          "thumb_width": 80,
          "title": "House for sale, Lea Bridge - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_property_for_sale_112856078090247365.jpg",
          "img_width": 400,
          "keywords": "Garden, Conversion, Double Bedroom, Kitchen",
          "latitude": 51.58713,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856078090247365/title/5/1-19?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.099691,
          "price": 399950,
          "price_currency": "£",
          "price_formatted": "£399,950",
          "price_high": 399950,
          "price_low": 399950,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "A 2 bedroom period conversion, set on the ground floor, finished to...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_property_for_sale_112856078090247365.jpg",
          "thumb_width": 80,
          "title": "St Margarets Avenue - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_house_for_sale_112856073380636869.jpg",
          "img_width": 400,
          "keywords": "Freehold, Garden, Terraced, Double Bedroom, Kitchen, Off Street Parking",
          "latitude": 51.387188,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856073380636869/title/5/1-20?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.074585,
          "price": 249950,
          "price_currency": "£",
          "price_formatted": "£249,950",
          "price_high": 249950,
          "price_low": 249950,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "Good size, one double bedroom, end of terrace house with freehold. ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_house_for_sale_112856073380636869.jpg",
          "thumb_width": 80,
          "title": "House for sale, Goodhew Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_house_for_sale_112856073142472564.jpg",
          "img_width": 400,
          "keywords": "Garden, No Chain, Terraced, Kitchen, Gas Central Heating",
          "latitude": 51.483994,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856073142472564/title/5/1-21?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.080679,
          "price": 350000,
          "price_currency": "£",
          "price_formatted": "£350,000",
          "price_high": 350000,
          "price_low": 350000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Three bedroomed mid terrace period home for sale. The house is situ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_house_for_sale_112856073142472564.jpg",
          "thumb_width": 80,
          "title": "House for sale, Burwash Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_house_for_sale_112856074844952985.jpg",
          "img_width": 400,
          "keywords": "Shared Garden, Detached, Conversion, Fireplace, Victorian, Double Bedroom, Kitchen, Parking",
          "latitude": 51.43874,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856074844952985/title/5/1-22?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.018906,
          "price": 219995,
          "price_currency": "£",
          "price_formatted": "£219,995",
          "price_high": 219995,
          "price_low": 219995,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "Ly presented 1 bedroom conversion flat. Set within a semi detached ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_house_for_sale_112856074844952985.jpg",
          "thumb_width": 80,
          "title": "House for sale, Bromley Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_house_for_sale_112856074420353032.jpg",
          "img_width": 400,
          "keywords": "Detached, Garden, Conversion, Detached Garage, Terraced, Kitchen, Patio, Gas Central Heating",
          "latitude": 51.472603,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856074420353032/title/5/1-23?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.064192,
          "price": 420000,
          "price_currency": "£",
          "price_formatted": "£420,000",
          "price_high": 420000,
          "price_low": 420000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Off street parking for two cars extended kitchen bonus loft room ga...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_house_for_sale_112856074420353032.jpg",
          "thumb_width": 80,
          "title": "House for sale, Donaldson Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856075886721105.jpg",
          "img_width": 400,
          "keywords": "En suite, Penthouse, Double Bedroom, Kitchen, Lift, Gas Central Heating",
          "latitude": 51.48376,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856075886721105/title/5/1-24?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.070975,
          "price": 399995,
          "price_currency": "£",
          "price_formatted": "£399,995",
          "price_high": 399995,
          "price_low": 399995,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "A mile to woolwich DLR and mainline station top floor penthouse vau...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856075886721105.jpg",
          "thumb_width": 80,
          "title": "Bloomfield Road - En Suite, Lift",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_house_for_sale_112856075274485621.jpg",
          "img_width": 400,
          "keywords": "Garden, No Chain, Victorian, Kitchen, Reception, Gas Central Heating",
          "latitude": 51.483414,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856075274485621/title/5/1-25?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.06877,
          "price": 469995,
          "price_currency": "£",
          "price_formatted": "£469,995",
          "price_high": 469995,
          "price_low": 469995,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Offered with no forward chain two large separate reception rooms gr...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_house_for_sale_112856075274485621.jpg",
          "thumb_width": 80,
          "title": "House for sale, Elmdene Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856075522645502.jpg",
          "img_width": 400,
          "keywords": "Garden, Conversion, High Ceilings, Refurbished, Victorian, Double Bedroom, Kitchen, Reception, Gas Central Heating",
          "latitude": 51.483105,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856075522645502/title/5/1-26?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.301606,
          "price": 365000,
          "price_currency": "£",
          "price_formatted": "£365,000",
          "price_high": 365000,
          "price_low": 365000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Ground floor victorian conversion condition open-plan reception pri...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856075522645502.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Heath Road - Reception",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112856073055857436.jpg",
          "img_width": 400,
          "keywords": "Garden, Conservatory, Fireplace, Kitchen, Loft, Parking, Patio",
          "latitude": 51.4625,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856073055857436/title/5/1-27?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.044932,
          "price": 375000,
          "price_currency": "£",
          "price_formatted": "£375,000",
          "price_high": 375000,
          "price_low": 375000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "15ft living room 18ft kitchen conservatory first floor bathroom 65f...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112856073055857436.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Appleton Road - Patio",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856073740927054.jpg",
          "img_width": 400,
          "keywords": "Balcony, Double Bedroom",
          "latitude": 51.522083,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856073740927054/title/5/1-28?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.0874662,
          "price": 399995,
          "price_currency": "£",
          "price_formatted": "£399,995",
          "price_high": 399995,
          "price_low": 399995,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Property summary moments from the DLR, with a private balcony offer...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856073740927054.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Gill Street - Balcony",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 4,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/4_bedrooms_property_for_sale_112856072652264227.jpg",
          "img_width": 400,
          "keywords": "En suite, Garage, Kitchen, Reception",
          "latitude": 51.622993,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856072652264227/title/5/1-29?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.262092,
          "price": 540000,
          "price_currency": "£",
          "price_formatted": "£540,000",
          "price_high": 540000,
          "price_low": 540000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 4,
          "size": 0,
          "size_type": "net",
          "summary": "A four bedroom extended family home located moments away from the t...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/4_bedrooms_property_for_sale_112856072652264227.jpg",
          "thumb_width": 80,
          "title": "Property for sale, Riverdene",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112856075497315114.jpg",
          "img_width": 400,
          "keywords": "Shared Garden, No Chain, Conversion, Double Bedroom, Kitchen, Off Street Parking, Reception",
          "latitude": 51.443695,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856075497315114/title/5/1-30?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.065636,
          "price": 500000,
          "price_currency": "£",
          "price_formatted": "£500,000",
          "price_high": 500000,
          "price_low": 500000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "An and andnbsp;three double bedroom period conversion measuring 856...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112856075497315114.jpg",
          "thumb_width": 80,
          "title": "Property for sale, Underhill Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112856075330211936.jpg",
          "img_width": 400,
          "keywords": "Garden, Conservatory, Kitchen, Off Street Parking",
          "latitude": 51.56235,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856075330211936/title/5/1-31?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.299016,
          "price": 530000,
          "price_currency": "£",
          "price_formatted": "£530,000",
          "price_high": 530000,
          "price_low": 530000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "A 1930's built semidetached family home located in north wembley lo...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112856075330211936.jpg",
          "thumb_width": 80,
          "title": "Property for sale, East Lane - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856072234297198.jpg",
          "img_width": 400,
          "keywords": "Garden, Penthouse, Balcony, Gym, Porter, Swimming Pool",
          "latitude": 51.509476,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856072234297198/title/5/1-32?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.005619,
          "price": 620000,
          "price_currency": "£",
          "price_formatted": "£620,000",
          "price_high": 620000,
          "price_low": 620000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "5th floor | esat facing | river facing views | 844 sqft plus balcon...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856072234297198.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Defoe House - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112800357491717662.jpg",
          "img_width": 400,
          "keywords": "Auction, Conversion, Victorian, Double Bedroom, Kitchen, Reception",
          "latitude": 51.453426,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112800357491717662/title/5/1-33?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.231392,
          "price": 215000,
          "price_currency": "£",
          "price_formatted": "£215,000",
          "price_high": 215000,
          "price_low": 215000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "One bedroom building good condition good transport links original f...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112800357491717662.jpg",
          "thumb_width": 80,
          "title": "Leamington Park - Double Bedroom",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_property_for_sale_112856069570114953.jpg",
          "img_width": 400,
          "keywords": "Double Bedroom, Kitchen",
          "latitude": 51.57132,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856069570114953/title/5/1-34?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.084838,
          "price": 260000,
          "price_currency": "£",
          "price_formatted": "£260,000",
          "price_high": 260000,
          "price_low": 260000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Second floor flat two double bedrooms modern bathroom suite bright ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_property_for_sale_112856069570114953.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Lynn Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856068294870681.jpg",
          "img_width": 400,
          "keywords": "En suite, Balcony, Modern",
          "latitude": 51.54166,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856068294870681/title/5/1-35?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.262674,
          "price": 400000,
          "price_currency": "£",
          "price_formatted": "£400,000",
          "price_high": 400000,
          "price_low": 400000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Located on the third floor of a modern development in harlesden thi...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856068294870681.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Hilltop Avenue",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856070026220086.jpg",
          "img_width": 400,
          "keywords": "",
          "latitude": 51.54574,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856070026220086/title/5/1-36?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.23015,
          "price": 475000,
          "price_currency": "£",
          "price_formatted": "£475,000",
          "price_high": 475000,
          "price_low": 475000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "This smart two bedroom flat offers accommodation throughout and ben...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856070026220086.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Harlesden Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112856068863290007.jpg",
          "img_width": 400,
          "keywords": "Shared Garden, Modern",
          "latitude": 51.478138,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856068863290007/title/5/1-37?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.278,
          "price": 350000,
          "price_currency": "£",
          "price_formatted": "£350,000",
          "price_high": 350000,
          "price_low": 350000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "Set within this prestigious development, this modern 1 bedroom flat...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112856068863290007.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Melliss Avenue",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_property_for_sale_112856070528679846.jpg",
          "img_width": 400,
          "keywords": "Garden, Conversion, High Ceilings",
          "latitude": 51.420856,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856070528679846/title/5/1-38?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.081872,
          "price": 475000,
          "price_currency": "£",
          "price_formatted": "£475,000",
          "price_high": 475000,
          "price_low": 475000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Guide andpound;450,000 andpound;475,000 a well appointed two bedroo...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_property_for_sale_112856070528679846.jpg",
          "thumb_width": 80,
          "title": "Camden Hill Road - Garden, Conversion",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 2,
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856070908053915.jpg",
          "img_width": 400,
          "keywords": "En suite, Kitchen, Parking",
          "latitude": 51.566494,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856070908053915/title/5/1-39?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.296379,
          "price": 379950,
          "price_currency": "£",
          "price_formatted": "£379,950",
          "price_high": 379950,
          "price_low": 379950,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Two bedroom ground floor flat with two bedrooms and two bathrooms a...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856070908053915.jpg",
          "thumb_width": 80,
          "title": "CHAMBERLAYNE AVENUE - En Suite",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 2,
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856070558650455.jpg",
          "img_width": 400,
          "keywords": "En suite, Balcony, Kitchen, Parking, Shared Ownership",
          "latitude": 51.538616,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856070558650455/title/5/1-40?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.299324,
          "price": 176000,
          "price_currency": "£",
          "price_formatted": "£176,000",
          "price_high": 176000,
          "price_low": 176000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "A great opportunity for first time buyers to get onto the property ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856070558650455.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, HATTON ROAD - Balcony",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 2,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_house_for_sale_112856072463634279.jpg",
          "img_width": 400,
          "keywords": "Freehold, Garden, No Chain, Conversion, Refurbished, Terraced, Double Bedroom, Kitchen, Off Street Parking, Dishwasher, Reception",
          "latitude": 51.554386,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856072463634279/title/5/1-41?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.082231,
          "price": 435000,
          "price_currency": "£",
          "price_formatted": "£435,000",
          "price_high": 435000,
          "price_low": 435000,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Newly refurbished 3 bedroom, 2 bathrooms, 2 reception terraced hous...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_house_for_sale_112856072463634279.jpg",
          "thumb_width": 80,
          "title": "House for sale, Windsor Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_house_for_sale_112856071779847466.jpg",
          "img_width": 400,
          "keywords": "Garden, No Chain, Double Bedroom, Kitchen, Modern, Reception",
          "latitude": 51.384335,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856071779847466/title/5/1-42?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.077881,
          "price": 399950,
          "price_currency": "£",
          "price_formatted": "£399,950",
          "price_high": 399950,
          "price_low": 399950,
          "price_type": "fixed",
          "property_type": "house",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "This two double bedroom house is situated in a residential location...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_house_for_sale_112856071779847466.jpg",
          "thumb_width": 80,
          "title": "House for sale, Jesmond Road - Modern",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 4,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/4_bedrooms_property_for_sale_112856071892661983.jpg",
          "img_width": 400,
          "keywords": "Garden, No Chain, Garage, Kitchen",
          "latitude": 51.509384,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856071892661983/title/5/1-43?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.112128,
          "price": 450000,
          "price_currency": "£",
          "price_formatted": "£450,000",
          "price_high": 450000,
          "price_low": 450000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 4,
          "size": 0,
          "size_type": "net",
          "summary": "Chain free three bedrooms and bonus room greatly improved flexible ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/4_bedrooms_property_for_sale_112856071892661983.jpg",
          "thumb_width": 80,
          "title": "Greenhaven Drive - Garden, No Chain",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112856068903238668.jpg",
          "img_width": 400,
          "keywords": "Leasehold, Shared Garden, Balcony, Kitchen",
          "latitude": 51.53993,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856068903238668/title/5/1-44?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.078671,
          "price": 340000,
          "price_currency": "£",
          "price_formatted": "£340,000",
          "price_high": 340000,
          "price_low": 340000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "This luxury one-bedroom apartment located on the 22nd floor is now ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112856068903238668.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Cambridge Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 1,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112856069405892255.jpg",
          "img_width": 400,
          "keywords": "Leasehold, Shared Garden, Balcony, Kitchen",
          "latitude": 51.53993,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856069405892255/title/5/1-45?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": 0.078671,
          "price": 335000,
          "price_currency": "£",
          "price_formatted": "£335,000",
          "price_high": 335000,
          "price_low": 335000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 1,
          "size": 0,
          "size_type": "net",
          "summary": "This luxury one-bedroom apartment located on the 23rd floor is now ...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112856069405892255.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Cambridge Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856071889191167.jpg",
          "img_width": 400,
          "keywords": "Shared Garden, Balcony, Kitchen",
          "latitude": 51.49366,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856071889191167/title/5/1-46?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.20672697,
          "price": 435000,
          "price_currency": "£",
          "price_formatted": "£435,000",
          "price_high": 435000,
          "price_low": 435000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "Getanoffer are offering this ly priced property from a motivated se...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856071889191167.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Lisgar Terrace",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 2,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/2_bedrooms_flat_for_sale_112856070111649191.jpg",
          "img_width": 400,
          "keywords": "Garden, Reception",
          "latitude": 51.5519,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856070111649191/title/5/1-47?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.240873,
          "price": 375000,
          "price_currency": "£",
          "price_formatted": "£375,000",
          "price_high": 375000,
          "price_low": 375000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 2,
          "size": 0,
          "size_type": "net",
          "summary": "This 2 bedroom ground floor flats offers bright and contemporary li...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/2_bedrooms_flat_for_sale_112856070111649191.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Cooper Road - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": "",
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112856069613109996.jpg",
          "img_width": 400,
          "keywords": "Garden, Needs Modernisation, Auction, No Chain, Fireplace, Kitchen, Off Street Parking, Modern, Reception",
          "latitude": 51.384945,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856069613109996/title/5/1-48?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.179621,
          "price": 290000,
          "price_currency": "£",
          "price_formatted": "£290,000",
          "price_high": 290000,
          "price_low": 290000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "For sale by modern method of auction starting bid 290,000 plus rese...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112856069613109996.jpg",
          "thumb_width": 80,
          "title": "Property for sale, Tweeddale Road",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 1,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_flat_for_sale_112856071570399062.jpg",
          "img_width": 400,
          "keywords": "Garden, Maisonette, Victorian, Reception",
          "latitude": 51.43694,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856071570399062/title/5/1-49?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.120896,
          "price": 525000,
          "price_currency": "£",
          "price_formatted": "£525,000",
          "price_high": 525000,
          "price_low": 525000,
          "price_type": "fixed",
          "property_type": "flat",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Hailsham avenue streatham, sw2 525,000 3 bedrooms 1 bathroom 2 rece...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_flat_for_sale_112856071570399062.jpg",
          "thumb_width": 80,
          "title": "Flat for sale, Streatham - Garden",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        },
        {
          "bathroom_number": 6,
          "bedroom_number": 3,
          "car_spaces": "",
          "commission": 0,
          "construction_year": 0,
          "datasource_name": "OneDome",
          "img_height": 300,
          "img_url": "https://imgs.nestimg.com/3_bedrooms_property_for_sale_112856069608600321.jpg",
          "img_width": 400,
          "keywords": "Garden, Kitchen",
          "latitude": 51.468876,
          "lister_url": "https://www.nestoria.co.uk/detail/0000000112856069608600321/title/5/1-50?serpUid=&pt=1&ot=1&l=london&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",
          "listing_type": "buy",
          "location_accuracy": 9,
          "longitude": -0.015311,
          "price": 375000,
          "price_currency": "£",
          "price_formatted": "£375,000",
          "price_high": 375000,
          "price_low": 375000,
          "price_type": "fixed",
          "property_type": "property",
          "room_number": 3,
          "size": 0,
          "size_type": "net",
          "summary": "Kitchen/diner 10' 6andquot; x 9' 9andquot; andnbsp; living room 18'...",
          "thumb_height": 60,
          "thumb_url": "https://imgs.nestimg.com/medium/3_bedrooms_property_for_sale_112856069608600321.jpg",
          "thumb_width": 80,
          "title": "Property for sale, Russett Way",
          "updated_in_days": 1,
          "updated_in_days_formatted": "New"
        }
      ],
      "locations": [
        {
          "center_lat": 51.527243,
          "center_long": -0.106841,
          "long_title": "London",
          "place_name": "london",
          "title": "London"
        }
      ],
      "page": 1,
      "sort": "newest",
      "status_code": "200",
      "status_text": "OK",
      "thanks": "For using the Nestoria API.",
      "total_pages": 796,
      "total_results": 39775,
      "_cu5t0mP434m_": "remove"
    }
  }